name: Build

on:
  push:
    branches:
      - main
    paths:
      - "**.nix"
      - flake.lock
      - .github/workflows/*.yml
  pull_request:
    branches:
      - main
    paths:
      - "**.nix"
      - flake.lock
      - .github/workflows/*.yml
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: |
          curl --proto '=https' --tlsv1.2 -sSf -L https://install.lix.systems/lix | sh -s -- install --no-confirm
          echo "trusted-users = root runner" | sudo tee -a /etc/nix/nix.conf

      - uses: DeterminateSystems/magic-nix-cache-action@v8

      - run: nix build
