name: Update

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  update:
    name: XIVLauncher-RB Update
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v15
        with:
          source-url: https://install.lix.systems/lix/lix-installer-x86_64-linux
          diagnostic-endpoint: ""

      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Configure git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - run: nix run github:Mic92/nix-update -- xivlauncher-rb --flake --commit --version-regex 'rb-v(.*)'

      - id: create-pr
        uses: peter-evans/create-pull-request@v7
        with:
          branch: update_xivlauncher-rb
          delete-branch: true
          committer: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
          author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
          commit-message: 'pkgs: update xivlauncher-rb'
          title: 'pkgs: update xivlauncher-rb'
          labels: 'dependencies'
          body: |
            Automated bump of XIVLauncher-RB

      - uses: benc-uk/workflow-dispatch@v1
        if: ${{ contains(fromJSON('["created", "updated"]'), steps.create-pr.outputs.pull-request-operation) }}
        with:
          workflow: build.yml
          ref: refs/heads/update_xivlauncher-rb
